title: Java programming language
description: > # this means to ignore newlines until "baseurl:"
  Course of Java programming language, useful for Professional Training Modules such
  as Multi Platform Application Development or Web Application Development. Written
  by Nacho Iborra, Mari Chelo Rubio and Javier Carrasco, professional training teachers
  at I.E.S. San Vicente (San Vicente del Raspeig, Alicante, Spain)
baseurl: "/java" # the subpath of your site, e.g. /blog
url: "http://nachoiborraIES.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown